package com.shinhan.day08;

public class ExceptionTest {
	public static void main(String[] args) {
		method1(0);
	}

	private static void method1(int count) {
		//예외 : 1)RuntimeException...실행 시 오류발생 2)일반Exception
		int score = 100;
		
		//if(count == 0) return;
		//오류처리로직과 비즈니스로직 처리가 섞인다. 권장하지 않음
		
		try {
			System.out.println("평균은 " + score/count);
		} catch(ArithmeticException ex) {
			//Exception 처리함...그러므로 프로그램 중단없이 계속 진행된다.
			System.out.println("연산오류....." + ex.getMessage());
		}
	}
}
